name: Run tests

on:
  push:
    branches:
      - test-pipeline
  pull_request:
    branches:
      - test-pipeline

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: almalinux:9
    steps:
      - uses: actions/checkout@v4
      - name: Install Python and dependencies
        run: |
          dnf update -y
          dnf install -y python39 python39-pip python39-devel gcc
      - name: Setup environment
        run: |
          python -m pip install .[dev]
      - name: Run pytest
        run: |
          pytest tests/
